/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-11-22 12:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ejemplos.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class box_002dmodel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/includes/navigation.jsp", Long.valueOf(1574427011686L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1574426797183L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1574425065338L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

String titulo = "HelloWeb | box-model";
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> <!-- html5 -->\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>");
      out.print(titulo);
      out.write("</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat|Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <base href=\"/PruebaTecnica/\"> -->\r\n");
      out.write("    <base href=\"/helloweb/\">\r\n");
      out.write("    <!-- estilos -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css?time=");
      out.print(System.currentTimeMillis());
      out.write("\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>");
      out.write('\r');
      out.write('\n');
      out.write("<header class=\"nav-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"topnav\" id=\"myTopnav\">\r\n");
      out.write("        <a href=\"index.jsp\" class=\"active\">Inicio</a>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <button class=\"dropbtn\">CSS\r\n");
      out.write("                <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"ejemplos/css/animaciones.jsp\">Animaciones</a>\r\n");
      out.write("                <a href=\"ejemplos/css/basico.jsp\">Basico</a>\r\n");
      out.write("                <a href=\"ejemplos/css/especificidad.jsp\">Especificidad</a>\r\n");
      out.write("                <a href=\"ejemplos/css/avanzado.jsp\">Avanzado</a>\r\n");
      out.write("                <a href=\"ejemplos/css/flexbox.jsp\">flexbox</a>\r\n");
      out.write("                <a href=\"ejemplos/css/media-querys.jsp\">media querys</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <button class=\"dropbtn\">HTML\r\n");
      out.write("                <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"ejemplos/html/box-model.jsp\">VisualizaciÃ³n</a>\r\n");
      out.write("                <a href=\"ejemplos/html/posicionamiento.jsp\">Posicionamiento</a>\r\n");
      out.write("                <a href=\"ejemplos/html/formulario.jsp\">Formularios</a>\r\n");
      out.write("                <a href=\"ejemplos/html/menu-responsive.jsp\">Menu-responsive</a>\r\n");
      out.write("                <a href=\"login.jsp\">Login</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <button class=\"dropbtn\">JavaScript\r\n");
      out.write("                <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"ejemplos/js/game.jsp\">Arkanoid</a>\r\n");
      out.write("                <a href=\"ejemplos/js/datatable.jsp\">Datatables</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <button class=\"dropbtn\">Utilidades\r\n");
      out.write("                <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"https://caniuse.com/\">caniuse</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"javascript:void(0);\" style=\"font-size:15px;\" class=\"icon\" onclick=\"myFunction()\">&#9776;</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function myFunction() {\r\n");
      out.write("            var x = document.getElementById(\"myTopnav\");\r\n");
      out.write("            if (x.className === \"topnav\") {\r\n");
      out.write("                x.className += \" responsive\";\r\n");
      out.write("            } else {\r\n");
      out.write("                x.className = \"topnav\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<main>");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        span {\r\n");
      out.write("            border: 3px dotted red;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p.prueba {\r\n");
      out.write("            color: teal;\r\n");
      out.write("            border: 5px solid green;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            /* padding: 20px;  */\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .box {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            /* para que el bloque ocupe el borde que especifiquemos\r\n");
      out.write("            sin que se le sume los 2px de los bordes */\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("\r\n");
      out.write("            border: 2px solid teal;\r\n");
      out.write("            background-color: royalblue;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 5em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .box-texto {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            border: 3px solid blueviolet;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        section {\r\n");
      out.write("        \tmargin: 0px 80px 0px 80px; \r\n");
      out.write("            border: 1px solid rgb(131, 131, 131);\r\n");
      out.write("            background-color: ghostwhite;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 50px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("\r\n");
      out.write("            -webkit-box-shadow: 8px 6px 6px -1px rgba(0, 0, 0, 0.27);\r\n");
      out.write("            -moz-box-shadow: 8px 6px 6px -1px rgba(0, 0, 0, 0.27);\r\n");
      out.write("            box-shadow: 8px 6px 6px -1px rgba(0, 0, 0, 0.27);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <h1>Visualización</h1>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2>Toda etiqueta de HTML tiene una estructura de caja</h2>\r\n");
      out.write("        <h2>Display</h2>\r\n");
      out.write("        <a href=\"index.jsp\">Volver</a>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"prueba\">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Alias earum accusantium labore\r\n");
      out.write("            voluptatem modi nemo eos\r\n");
      out.write("            quasi, consequatur rem porro ipsa cumque dignissimos minima repudiandae, incidunt, eligendi quas magnam\r\n");
      out.write("            voluptatum?</p>\r\n");
      out.write("\r\n");
      out.write("        <h3>Elementos en linea o bloque</h3>\r\n");
      out.write("        <p><code>display</code>Es el atributo para gestionar si es linea o bloque (existen mas displays ej flex)</p>\r\n");
      out.write("        <p>*trick: usar inspector para verlo</p>\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>block</dt>\r\n");
      out.write("            <dd>elemento que ocupa todo el ancho del elemento padre</dd>\r\n");
      out.write("\r\n");
      out.write("            <dt>inline</dt>\r\n");
      out.write("            <dd>elemento que ocupa todo lo que tenga su contenido</dd>\r\n");
      out.write("\r\n");
      out.write("            <dt>inline-block</dt>\r\n");
      out.write("            <dd>Es una mezcla entre las dos</dd>\r\n");
      out.write("\r\n");
      out.write("        </dl>\r\n");
      out.write("\r\n");
      out.write("        <p> <span> Lorem ipsum dolor </span> Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta tenetur\r\n");
      out.write("            fuga\r\n");
      out.write("            corrupti, dignissimos molestias sit\r\n");
      out.write("            consectetur ad, quod reprehenderit unde porro nam odit recusandae similique eum animi vero voluptatem\r\n");
      out.write("            deserunt.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">1</div>\r\n");
      out.write("        <div class=\"box\">2</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2>Visibility</h2>\r\n");
      out.write("        <p>Existen dos formas de ocultar elementos de html</p>\r\n");
      out.write("        <!-- Se oculta pero respeta el espacio -->\r\n");
      out.write("        <p>Usando <code>visibility</code></p>\r\n");
      out.write("        <div class=\"box\">1</div>\r\n");
      out.write("        <div class=\"box\" style=\"visibility:hidden\">2</div>\r\n");
      out.write("        <div class=\"box\">3</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Se oculta y no ocupa espacio -->\r\n");
      out.write("        <p>Usando <code>dislay:none</code></p>\r\n");
      out.write("        <div class=\"box\">1</div>\r\n");
      out.write("        <div class=\"box\" style=\"display:none\">2</div>\r\n");
      out.write("        <div class=\"box\">3</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2>Overflow</h2>\r\n");
      out.write("        <p> Como se muestra los elementos cuando no entran en el contenedor padre\r\n");
      out.write("            <code>[ visible | hidden | scroll | auto ]</code> </p>\r\n");
      out.write("        <p>Tambien se puede usar <code>overflow-x</code> y <code>ovyrflow-y</code></p>\r\n");
      out.write("        <div class=\"box-texto\" style=\"overflow: hidden;\">\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt laudantium ipsam facere explicabo in\r\n");
      out.write("                adipisci sed autem aliquid aspernatur magni neque, dolorem maiores! Quos praesentium dolorem inventore\r\n");
      out.write("                tenetur dolorum nam!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box-texto\" style=\"overflow: scroll;\">\r\n");
      out.write("            <p>Optio mollitia impedit dolore odio quisquam nisi perferendis autem provident aspernatur sit, voluptates\r\n");
      out.write("                inventore et quia repellendus assumenda nesciunt officia voluptatem, harum est saepe pariatur\r\n");
      out.write("                consequatur! Ea eum quos veniam.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box-texto\" style=\"overflow: auto;\">\r\n");
      out.write("            <p>Cumque modi qui suscipit at autem perferendis ullam tempore cum, culpa asperiores. Pariatur numquam\r\n");
      out.write("                provident velit facere quo vitae! Accusamus pariatur quaerat officia molestias ad fugit natus et\r\n");
      out.write("                dignissimos tempore!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box-texto\" style=\"overflow: visible;\">\r\n");
      out.write("            <p>Eos fugit laboriosam aut delectus, officiis corporis. Officiis, molestiae laborum culpa quis impedit\r\n");
      out.write("                minima eligendi fugit, unde nemo quae facere! Cumque laborum alias possimus, voluptas qui iste saepe ad\r\n");
      out.write("                eveniet.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2>Z-index</h2>\r\n");
      out.write("        <p>Se encarga de la profundidad de los elementos cuando se solapan</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\"\r\n");
      out.write("            style=\"background-color: chartreuse; position: relative; left: 278px; bottom: 22px; z-index: 2;\">1</div>\r\n");
      out.write("        <div class=\"box\" style=\"z-index: 0;position: relative; top:-20px; left:20px; background-color: brown;\">2</div>\r\n");
      out.write("        <div class=\"box\" style=\"z-index: 1;position: relative;\">3</div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("  ");
      out.write("</main>\r\n");
      out.write("<div class=\"footer-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-left\">\r\n");
      out.write("            <h2> <strong>Ipartek &copy</strong></h2>\r\n");
      out.write("            <h2>Juan Carlos San Celedonio</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-right\">\r\n");
      out.write("            <h2>Recursos:</h2>\r\n");
      out.write("            <a href=\"https://github.com/juancar92?tab=repositories\">\r\n");
      out.write("                <i class=\"fab fa-github fa-2x\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
